Repository Anipick-Team/anipick-backend, pull requests merged in 2025-08, with the labels that each got.

#217 fix/리뷰 조회 api의 user id 필드 추가
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsItemDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsResultDto.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/java/com/anipick/backend/home/dto/HomeRecentReviewItemDto.java
  src/main/java/com/anipick/backend/home/service/HomeService.java
  src/main/java/com/anipick/backend/review/dto/RecentReviewItemDto.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
  src/main/resources/mapper/home/HomeQueryMapper.xml
  src/main/resources/mapper/review/RecentReviewQueryMapper.xml
Labels: 버그 및 수정 🩹

#218 fix/리뷰 신고 API 신고 내용 추가
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/dto/ReviewReportMessageRequest.java
  src/main/java/com/anipick/backend/review/mapper/ReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/review/ReviewCommandMapper.xml
Labels: 버그 및 수정 🩹

#221 fix/마이페이지 이미지 관련 로직을 이미지 도메인으로 이동
  src/main/java/com/anipick/backend/image/mapper/ImageMapper.java
  src/main/java/com/anipick/backend/image/service/ImageService.java
  src/main/java/com/anipick/backend/mypage/service/MyPageService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/mapper/image/ImageCommandMapper.xml
Labels: 버그 및 수정 🩹, 리팩토링 ⚒️

#228 feat/소개 페이지 html 추가
  src/main/resources/asset/anipick_mascot.png
  src/main/resources/static/index.html
Labels: 기능 추가 🏗️, 문서 수정 📃

#229 fix/index.html 인가 허용
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
Labels: 버그 및 수정 🩹

#230 fix/소개 페이지 image 인가 허용
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/resources/static/image/anipick_mascot.png
  src/main/resources/static/index.html
Labels: 버그 및 수정 🩹, 리팩토링 ⚒️

#233 fix/소개 페이지 intro.html로 이름 변경
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/resources/static/intro.html
Labels: 버그 및 수정 🩹, 리팩토링 ⚒️

#244 feat/개인정보처리방침, 이용약관- 정적 페이지
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/resources/static/intro.html
  src/main/resources/static/privacy.html
  src/main/resources/static/terms.html
Labels: 기능 추가 🏗️

#182 fix/시리즈 테이블 스키마 변경으로 인한 시리즈 코드 변경
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: 버그 및 수정 🩹

#181 fix/인기순 정렬 테이블 정렬 코드 수정
  src/main/java/com/anipick/backend/anime/dto/ComingSoonItemPopularityDto.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/java/com/anipick/backend/common/domain/SortOption.java
  src/main/java/com/anipick/backend/explore/dto/ExploreItemDto.java
  src/main/java/com/anipick/backend/explore/dto/SignUpAnimeExploreSearchRequestDto.java
  src/main/java/com/anipick/backend/explore/dto/SignUpPopularAnimeItemDto.java
  src/main/java/com/anipick/backend/explore/service/ExploreService.java
  src/main/java/com/anipick/backend/explore/service/UserSignUpAnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
  src/main/resources/mapper/explore/UserSignUpAnimeQueryMapper.xml
Labels: 버그 및 수정 🩹

#243 fix/프로필 이미지 인가 허용
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/java/com/anipick/backend/image/service/ImageService.java
Labels: 버그 및 수정 🩹, 리팩토링 ⚒️

#212 fix/회원가입의 애니 평가 시 애니의 리뷰 평균 점수 업데이트
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/recommendation/mapper/UserRecommendStateMapper.java
  src/main/java/com/anipick/backend/review/dto/UserAnimeStatusInsertRequest.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/java/com/anipick/backend/user/mapper/UserAnimeStatusMapper.java
  src/main/resources/mapper/anime/AnimeCommandMapper.xml
  src/main/resources/mapper/recommendation/UserRecommendStateCommandMapper.xml
  src/main/resources/mapper/user/UserAnimeStatusCommandMapper.xml
Labels: 기능 추가 🏗️, 버그 및 수정 🩹

#247 fix/이미지 관련 로직 수정
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/java/com/anipick/backend/image/controller/ImageController.java
  src/main/java/com/anipick/backend/image/domain/DefaultImage.java
  src/main/java/com/anipick/backend/image/domain/ImageDefaults.java
  src/main/java/com/anipick/backend/image/dto/ImageIdResponse.java
  src/main/java/com/anipick/backend/image/service/ImageService.java
  src/main/java/com/anipick/backend/mypage/controller/MyPageController.java
  src/main/java/com/anipick/backend/mypage/service/MyPageService.java
  src/main/resources/static/image/default.jpg
Labels: 버그 및 수정 🩹, 리팩토링 ⚒️
