Repository Anipick-Team/anipick-backend, pull requests merged in 2025-07, with the labels that each got.

#154 feat/log util method 추가
  src/main/java/com/anipick/backend/log/domain/Area.java
  src/main/java/com/anipick/backend/log/domain/DefaultDataBody.java
  src/main/java/com/anipick/backend/log/domain/Page.java
  src/main/java/com/anipick/backend/log/domain/UserActionLog.java
  src/main/java/com/anipick/backend/log/utils/UrlSafeObjectDecoder.java
  src/main/java/com/anipick/backend/log/utils/UrlSafeObjectEncoder.java
  src/test/java/com/anipick/backend/log/utils/UrlSafeObjectDecoderTest.java
  src/test/java/com/anipick/backend/log/utils/UrlSafeObjectEncoderDecoderIntegrationTest.java
  src/test/java/com/anipick/backend/log/utils/UrlSafeObjectEncoderTest.java
Labels: feat

#132 fix/평가 삭제 수정 - 파라미터 삭제
  src/main/java/com/anipick/backend/review/controller/RatingController.java
  src/main/java/com/anipick/backend/review/mapper/RatingMapper.java
  src/main/java/com/anipick/backend/review/service/RatingService.java
Labels: fix

#134 feat/캐릭터성우 리스트 상세
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/domain/AnimeCharacterRole.java
  src/main/java/com/anipick/backend/anime/dto/AnimeCharacterActorPageDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeCharacterActorResultDto.java
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: feat

#158 feat/작품 검색 결과 시 로그 필드 추가
  src/main/java/com/anipick/backend/log/domain/UserActionLog.java
  src/main/java/com/anipick/backend/search/controller/SearchController.java
  src/main/java/com/anipick/backend/search/dto/SearchAnimePageDto.java
  src/main/java/com/anipick/backend/search/dto/SearchLogAnimeItemDto.java
  src/main/java/com/anipick/backend/search/service/SearchService.java
  src/test/java/com/anipick/backend/log/utils/UrlSafeObjectDecoderTest.java
  src/test/java/com/anipick/backend/log/utils/UrlSafeObjectEncoderDecoderIntegrationTest.java
  src/test/java/com/anipick/backend/log/utils/UrlSafeObjectEncoderTest.java
Labels: feat, fix

#148 feat/설정 - 닉네임 ,이메일, 비밀번호 변경
  src/main/java/com/anipick/backend/setting/controller/SettingController.java
  src/main/java/com/anipick/backend/setting/dto/ChangeEmailRequest.java
  src/main/java/com/anipick/backend/setting/dto/ChangeNicknameRequest.java
  src/main/java/com/anipick/backend/setting/dto/ChangePasswordRequest.java
  src/main/java/com/anipick/backend/setting/service/SettingService.java
  src/main/java/com/anipick/backend/setting/util/NicknameValidator.java
  src/main/java/com/anipick/backend/user/mapper/UserMapper.java
  src/main/resources/mapper/user/UserCommandMapper.xml
Labels: feat

#147 feat/마이페이지 - 좋아요한 애니, 성우
  src/main/java/com/anipick/backend/mypage/controller/MyPageController.java
  src/main/java/com/anipick/backend/mypage/dto/LikedAnimesDto.java
  src/main/java/com/anipick/backend/mypage/dto/LikedAnimesResponse.java
  src/main/java/com/anipick/backend/mypage/dto/LikedPersonsDto.java
  src/main/java/com/anipick/backend/mypage/dto/LikedPersonsResponse.java
  src/main/java/com/anipick/backend/mypage/dto/WatchingAnimesDto.java
  src/main/java/com/anipick/backend/mypage/mapper/MyPageMapper.java
  src/main/java/com/anipick/backend/mypage/service/MyPageService.java
  src/main/resources/mapper/mypage/MyPageQueryMapper.xml
Labels: feat

#151 feat/애니 평가의 조회 애니 (탐색 및 검색)
  src/main/java/com/anipick/backend/anime/mapper/MetaDataMapper.java
  src/main/java/com/anipick/backend/explore/controller/SignUpAnimeController.java
  src/main/java/com/anipick/backend/explore/dto/AnimeIdGenreDto.java
  src/main/java/com/anipick/backend/explore/dto/SignUpAnimeExploreSearchRequestDto.java
  src/main/java/com/anipick/backend/explore/dto/SignUpAnimeItemDto.java
  src/main/java/com/anipick/backend/explore/dto/SignUpPopularAnimeItemDto.java
  src/main/java/com/anipick/backend/explore/dto/UserSignUpAnimePageDto.java
  src/main/java/com/anipick/backend/explore/mapper/UserSignUpAnimeMapper.java
  src/main/java/com/anipick/backend/explore/service/UserSignUpAnimeService.java
  src/main/resources/mapper/anime/MetaDataQueryMapper.xml
  src/main/resources/mapper/explore/UserSignUpAnimeQueryMapper.xml
Labels: feat

#166 feat/유저의 애니 시청 상태 관리
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/user/controller/UserController.java
  src/main/java/com/anipick/backend/user/dto/UserAnimeStatusRequest.java
  src/main/java/com/anipick/backend/user/mapper/UserAnimeStatusMapper.java
  src/main/java/com/anipick/backend/user/service/UserAnimeStatusService.java
  src/main/resources/mapper/user/UserAnimeStatusCommandMapper.xml
Labels: feat

#177 fix/최근 리뷰 테스트 코드 수정
  src/test/java/com/anipick/backend/review/service/ReviewServiceTest.java
Labels: fix, test

#168 feat/리뷰 신고 및 유저 차단
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/dto/ReportReviewDto.java
  src/main/java/com/anipick/backend/review/mapper/ReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/java/com/anipick/backend/user/controller/BlockUserController.java
  src/main/java/com/anipick/backend/user/mapper/BlockUserMapper.java
  src/main/java/com/anipick/backend/user/service/BlockUserService.java
  src/main/resources/mapper/review/ReviewCommandMapper.xml
  src/main/resources/mapper/review/ReviewQueryMapper.xml
  src/main/resources/mapper/user/BlockUserCommandMapper.xml
  src/main/resources/mapper/user/BlockUserQueryMapper.xml
Labels: feat

#194 fix/추천 1 상세 referenceTitle 필드추가 및 추천, 탐색 api 요청 시 lastValue 타입 string 변경
  src/main/java/com/anipick/backend/explore/controller/ExploreController.java
  src/main/java/com/anipick/backend/explore/dto/ExploreItemDto.java
  src/main/java/com/anipick/backend/explore/dto/ExploreRequestDto.java
  src/main/java/com/anipick/backend/explore/service/ExploreService.java
  src/main/java/com/anipick/backend/recommendation/controller/RecommendController.java
  src/main/java/com/anipick/backend/recommendation/dto/UserMainRecommendationPageDto.java
  src/main/java/com/anipick/backend/recommendation/service/RecommendService.java
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
Labels: fix

#198 feat/해당 애니의 리뷰 작성 및 수정에 필요한 내 리뷰 데이터 조회
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/dto/MyReviewProviderResultDto.java
  src/main/java/com/anipick/backend/review/mapper/ReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/review/ReviewQueryMapper.xml
Labels: feat

#200 fix/TAG_BASED 상태일 때 리뷰가 없는 경우 빈값 리턴
  src/main/java/com/anipick/backend/recommendation/service/RecommendService.java
Labels: 버그 및 수정 🩹

#202 fix/isSpoiler 제거 및 카운트 쿼리 변경
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsRequestDto.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: 버그 및 수정 🩹

#204 fix/해당 애니의 리뷰작성 및 수정 시 자신의 평점(리뷰) 조회 API 시 응답 isSpoiler 필드 추가
  src/main/java/com/anipick/backend/review/dto/MyReviewProviderResultDto.java
  src/main/resources/mapper/review/ReviewQueryMapper.xml
Labels: 버그 및 수정 🩹

#206 fix/리뷰 찾기 파라미터에 맞는 메서드명 변경 및 생성
  src/main/java/com/anipick/backend/review/mapper/ReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/review/ReviewQueryMapper.xml
Labels: 버그 및 수정 🩹
