Repository Anipick-Team/anipick-backend, pull requests merged in 2025-09, with the labels that each got.

#253 fix/리뷰 유저 프로필 가져오기 (이미지 api 배포 후 버전)
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
  src/main/resources/mapper/review/RecentReviewQueryMapper.xml
Labels: 버그 및 수정 🩹

#264 fix/성우가 참여한 캐릭터 수 쿼리 변경
  src/main/java/com/anipick/backend/person/controller/PersonController.java
  src/main/resources/mapper/person/PersonQueryMapper.xml
Labels: 버그 및 수정 🩹

#266 fix/캐릭터&성우 조회 시 일본 성우만 조회
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: 버그 및 수정 🩹

#263 fix/pao 테이블 삭제로 인한 인기순 코드 변경
  src/main/java/com/anipick/backend/common/domain/SortOption.java
  src/main/java/com/anipick/backend/mypage/service/MyPageService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
Labels: 버그 및 수정 🩹, 리팩토링 ⚒️

#278 fix/성우 참여한 캐릭터&작품 리스트 페이징 수정
  src/main/java/com/anipick/backend/person/dto/PersonAnimeWorkAllTitleAndNameDto.java
  src/main/java/com/anipick/backend/person/service/PersonService.java
  src/main/resources/mapper/person/PersonQueryMapper.xml
Labels: 버그 및 수정 🩹

#286 fix/연도-분기에 맞게 애니가 나오도록 로직 수정
  src/main/java/com/anipick/backend/ranking/mapper/RankingMapper.java
  src/main/java/com/anipick/backend/ranking/service/RankingService.java
  src/main/resources/mapper/ranking/RankingQueryMapper.xml
  src/main/resources/static/intro.js
Labels: 도와주세요 🙇‍♂️, 버그 및 수정 🩹

#291 fix/리뷰 개수 값이 0일 때 if문 분기 나누기 처리
  src/main/java/com/anipick/backend/review/service/ReviewService.java
Labels: 버그 및 수정 🩹

#296 fix/성인 애니 제거(추천, 탐색, 검색, 공개예정)
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/dto/ComingSoonRequestDto.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/java/com/anipick/backend/explore/dto/SignUpAnimeExploreSearchRequestDto.java
  src/main/java/com/anipick/backend/explore/service/UserSignUpAnimeService.java
  src/main/java/com/anipick/backend/home/service/HomeService.java
  src/main/java/com/anipick/backend/recommendation/service/RecommendService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
  src/main/resources/mapper/explore/UserSignUpAnimeQueryMapper.xml
  src/main/resources/mapper/home/HomeQueryMapper.xml
  src/main/resources/mapper/recommendation/RecommendMapper.xml
  src/main/resources/mapper/search/SearchQueryMapper.xml
Labels: 버그 및 수정 🩹

#298 fix/랭킹에서 성인 애니 제거
  src/main/resources/mapper/ranking/RankingQueryMapper.xml
  src/main/resources/mapper/ranking/RealTimeRankingQueryMapper.xml
Labels: 버그 및 수정 🩹
