Repository Anipick-Team/anipick-backend, pull requests merged in 2025-05, with the labels that each got.

#3 feat/global exception 및 api response 응답 표준화
  src/main/java/com/anipick/backend/common/dto/ApiResponse.java
  src/main/java/com/anipick/backend/common/exception/CustomException.java
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/common/exception/GlobalExceptionHandler.java
Labels: feat

#9 feat/최근 리뷰들 조회
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/dto/CursorDto.java
  src/main/java/com/anipick/backend/review/dto/RecentReviewItemDto.java
  src/main/java/com/anipick/backend/review/dto/RecentReviewPageDto.java
  src/main/java/com/anipick/backend/review/mapper/RecentReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/review/ReviewQueryMapper.xml
  src/test/java/com/anipick/backend/review/service/ReviewServiceTest.java
Labels: feat

#11 feat/메타 데이터 API
  src/main/java/com/anipick/backend/anime/controller/MetaDataController.java
  src/main/java/com/anipick/backend/anime/domain/AnimeFormat.java
  src/main/java/com/anipick/backend/anime/domain/Season.java
  src/main/java/com/anipick/backend/anime/dto/GenreDto.java
  src/main/java/com/anipick/backend/anime/dto/MetaDataGroupResultDto.java
  src/main/java/com/anipick/backend/anime/dto/SeasonDto.java
  src/main/java/com/anipick/backend/anime/mapper/MetaDataMapper.java
  src/main/java/com/anipick/backend/anime/service/MetaDataService.java
  src/main/resources/mapper/anime/MetaDataQueryMapper.xml
Labels: feat

#14 fix/Cursor sort 필드 추가 & 레이어 변경 & of 메서드 추가
  src/main/java/com/anipick/backend/common/dto/CursorDto.java
  src/main/java/com/anipick/backend/review/dto/CursorDto.java
  src/main/java/com/anipick/backend/review/dto/RecentReviewPageDto.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
Labels: fix

#18 Feat/17 local 회원가입 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/anipick/backend/common/auth/JwtAuthFilter.java
  src/main/java/com/anipick/backend/common/auth/JwtTokenProvider.java
  src/main/java/com/anipick/backend/common/auth/dto/CustomUserDetails.java
  src/main/java/com/anipick/backend/common/auth/service/CustomUserDetailsService.java
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/user/controller/UserController.java
  src/main/java/com/anipick/backend/user/domain/LoginFormat.java
  src/main/java/com/anipick/backend/user/domain/User.java
  src/main/java/com/anipick/backend/user/domain/UserDefaults.java
  src/main/java/com/anipick/backend/user/dto/SignUpRequest.java
  src/main/java/com/anipick/backend/user/mapper/UserMapper.java
  src/main/java/com/anipick/backend/user/service/NicknameInitializer.java
  src/main/java/com/anipick/backend/user/service/SignUpValidator.java
  src/main/java/com/anipick/backend/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/mapper/user/UserCommandMapper.xml
  src/main/resources/mapper/user/UserQueryMapper.xml
Labels: feat

#20 feat/탐색 기능 추가
  src/main/java/com/anipick/backend/anime/common/dto/AnimeItemDto.java
  src/main/java/com/anipick/backend/anime/common/util/FormatConvert.java
  src/main/java/com/anipick/backend/common/domain/SortOption.java
  src/main/java/com/anipick/backend/common/dto/CursorDto.java
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/explore/controller/ExploreController.java
  src/main/java/com/anipick/backend/explore/domain/GenresOption.java
  src/main/java/com/anipick/backend/explore/dto/ExploreItemDto.java
  src/main/java/com/anipick/backend/explore/dto/ExplorePageDto.java
  src/main/java/com/anipick/backend/explore/dto/ExploreRequestDto.java
  src/main/java/com/anipick/backend/explore/mapper/ExploreMapper.java
  src/main/java/com/anipick/backend/explore/service/ExploreService.java
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
  src/test/java/com/anipick/backend/explore/service/ExploreServiceTest.java
Labels: feat

#31 refactor/dto 레이어 이동
  src/main/java/com/anipick/backend/anime/controller/MetaDataController.java
  src/main/java/com/anipick/backend/anime/controller/dto/MetaDataGroupResultDto.java
  src/main/java/com/anipick/backend/anime/mapper/MetaDataMapper.java
  src/main/java/com/anipick/backend/anime/service/MetaDataService.java
  src/main/java/com/anipick/backend/anime/service/dto/GenreDto.java
  src/main/java/com/anipick/backend/anime/service/dto/SeasonDto.java
  src/main/java/com/anipick/backend/explore/controller/ExploreController.java
  src/main/java/com/anipick/backend/explore/controller/dto/ExplorePageDto.java
  src/main/java/com/anipick/backend/explore/mapper/ExploreMapper.java
  src/main/java/com/anipick/backend/explore/service/ExploreService.java
  src/main/java/com/anipick/backend/explore/service/dto/ExploreItemDto.java
  src/main/java/com/anipick/backend/explore/service/dto/ExploreRequestDto.java
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/controller/dto/RecentReviewPageDto.java
  src/main/java/com/anipick/backend/review/mapper/RecentReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/java/com/anipick/backend/review/service/dto/RecentReviewItemDto.java
  src/main/java/com/anipick/backend/user/controller/UserController.java
  src/main/java/com/anipick/backend/user/controller/dto/SignUpRequest.java
  src/main/java/com/anipick/backend/user/service/UserService.java
  src/main/resources/mapper/anime/MetaDataQueryMapper.xml
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
  src/main/resources/mapper/review/ReviewQueryMapper.xml
  src/test/java/com/anipick/backend/review/service/ReviewServiceTest.java
Labels: refactor

#34 feat/방영 예정 기능 추가
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/controller/dto/UpcomingSeasonResultDto.java
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/java/com/anipick/backend/anime/service/dto/AnimeIdTitleImgItemDto.java
  src/main/java/com/anipick/backend/anime/service/dto/RangeDateRequestDto.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: feat

#36 Feat/32 redis 기본 설정
  build.gradle
  src/main/java/com/anipick/backend/common/config/RedisCacheConfig.java
  src/main/java/com/anipick/backend/common/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: chore

#37 feat/공개예정 리스트 조회
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/controller/MetaDataController.java
  src/main/java/com/anipick/backend/anime/dto/AnimeIdTitleImgItemDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeItemDto.java
  src/main/java/com/anipick/backend/anime/dto/ComingSoonItemBasicDto.java
  src/main/java/com/anipick/backend/anime/dto/ComingSoonItemDto.java
  src/main/java/com/anipick/backend/anime/dto/ComingSoonItemPopularityDto.java
  src/main/java/com/anipick/backend/anime/dto/ComingSoonPageDto.java
  src/main/java/com/anipick/backend/anime/dto/ComingSoonRequestDto.java
  src/main/java/com/anipick/backend/anime/dto/GenreDto.java
  src/main/java/com/anipick/backend/anime/dto/MetaDataGroupResultDto.java
  src/main/java/com/anipick/backend/anime/dto/RangeDateRequestDto.java
  src/main/java/com/anipick/backend/anime/dto/SeasonDto.java
  src/main/java/com/anipick/backend/anime/dto/UpcomingSeasonResultDto.java
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/mapper/MetaDataMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/java/com/anipick/backend/anime/service/MetaDataService.java
  src/main/java/com/anipick/backend/anime/util/FormatConvert.java
  src/main/java/com/anipick/backend/explore/controller/ExploreController.java
  src/main/java/com/anipick/backend/explore/dto/ExploreItemDto.java
  src/main/java/com/anipick/backend/explore/dto/ExplorePageDto.java
  src/main/java/com/anipick/backend/explore/dto/ExploreRequestDto.java
  src/main/java/com/anipick/backend/explore/mapper/ExploreMapper.java
  src/main/java/com/anipick/backend/explore/service/ExploreService.java
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/dto/RecentReviewItemDto.java
  src/main/java/com/anipick/backend/review/dto/RecentReviewPageDto.java
  src/main/java/com/anipick/backend/review/mapper/RecentReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/application-local.yml
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
  src/main/resources/mapper/anime/MetaDataQueryMapper.xml
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
  src/main/resources/mapper/review/ReviewQueryMapper.xml
  src/test/java/com/anipick/backend/anime/service/dto/ComingSoonItemBasicDtoTest.java
  src/test/java/com/anipick/backend/review/service/ReviewServiceTest.java
Labels: feat

#43 Fix/format, 공개예정 메서드 list 변경, 최근 리뷰 조회 수정
  src/main/java/com/anipick/backend/anime/domain/AnimeFormat.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/review/ReviewQueryMapper.xml
Labels: fix

#38 feat/Local 로그인 기능 추가
  src/main/java/com/anipick/backend/common/config/RedisConfig.java
  src/main/java/com/anipick/backend/token/controller/TokenController.java
  src/main/java/com/anipick/backend/token/domain/RefreshToken.java
  src/main/java/com/anipick/backend/token/dto/TokenResponse.java
  src/main/java/com/anipick/backend/token/service/TokenService.java
  src/main/java/com/anipick/backend/user/controller/UserController.java
  src/main/java/com/anipick/backend/user/dto/LoginRequest.java
  src/main/java/com/anipick/backend/user/dto/SignUpRequest.java
  src/main/java/com/anipick/backend/user/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: feat

#46 feat/검색(작품 인물 제작사)
  src/main/java/com/anipick/backend/common/exception/ErrorCode.java
  src/main/java/com/anipick/backend/search/controller/SearchController.java
  src/main/java/com/anipick/backend/search/dto/PersonItemDto.java
  src/main/java/com/anipick/backend/search/dto/SearchAnimePageDto.java
  src/main/java/com/anipick/backend/search/dto/SearchPersonPageDto.java
  src/main/java/com/anipick/backend/search/dto/SearchStudioPageDto.java
  src/main/java/com/anipick/backend/search/dto/StudioItemDto.java
  src/main/java/com/anipick/backend/search/mapper/SearchMapper.java
  src/main/java/com/anipick/backend/search/service/SearchService.java
  src/main/resources/mapper/search/SearchQueryMapper.xml
Labels: feat

#49 fix/AnimeItemDto 클래스 필드명 변경
  src/main/java/com/anipick/backend/anime/dto/AnimeItemDto.java
  src/main/java/com/anipick/backend/search/service/SearchService.java
Labels: fix

#51 fix/33 local 로그아웃 기능 추가 및 JWTAuthFilter 수정
  src/main/java/com/anipick/backend/common/auth/JwtAuthFilter.java
  src/main/java/com/anipick/backend/common/auth/JwtTokenProvider.java
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/java/com/anipick/backend/user/controller/UserController.java
  src/main/java/com/anipick/backend/user/domain/UserDefaults.java
  src/main/java/com/anipick/backend/user/service/UserService.java
  src/main/resources/mapper/user/UserQueryMapper.xml
Labels: fix

#55 feat/유저 파라미터(인증) 추가
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/explore/controller/ExploreController.java
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/search/controller/SearchController.java
Labels: feat

#58 fix/검색 결과 타 탭 count
  src/main/java/com/anipick/backend/search/dto/SearchAnimePageDto.java
  src/main/java/com/anipick/backend/search/dto/SearchPersonPageDto.java
  src/main/java/com/anipick/backend/search/dto/SearchStudioPageDto.java
  src/main/java/com/anipick/backend/search/service/SearchService.java
Labels: fix

#62 fix/local 로그아웃 기능 수정
  src/main/java/com/anipick/backend/common/auth/JwtTokenProvider.java
  src/main/java/com/anipick/backend/token/service/TokenService.java
  src/main/java/com/anipick/backend/user/service/UserService.java
Labels: fix

#59 feat/검색 인덱스 화면 - 인기 작품 조회
  src/main/java/com/anipick/backend/search/controller/SearchController.java
  src/main/java/com/anipick/backend/search/dto/SearchInitPageDto.java
  src/main/java/com/anipick/backend/search/mapper/SearchMapper.java
  src/main/java/com/anipick/backend/search/service/SearchService.java
  src/main/resources/mapper/search/SearchQueryMapper.xml
Labels: feat
