Repository Anipick-Team/anipick-backend, pull requests merged in 2025-06, with the labels that each got.

#72 feat/소셜 로그인 애플 추가
  build.gradle
  src/main/java/com/anipick/backend/common/config/JacksonConfig.java
  src/main/java/com/anipick/backend/common/config/SecurityConfig.java
  src/main/java/com/anipick/backend/oauth/component/CommonLogin.java
  src/main/java/com/anipick/backend/oauth/component/GoogleVerifierProcessor.java
  src/main/java/com/anipick/backend/oauth/controller/OAuthController.java
  src/main/java/com/anipick/backend/oauth/domain/AppleDefaults.java
  src/main/java/com/anipick/backend/oauth/domain/KakaoDefaults.java
  src/main/java/com/anipick/backend/oauth/domain/Platform.java
  src/main/java/com/anipick/backend/oauth/domain/Provider.java
  src/main/java/com/anipick/backend/oauth/dto/SocialLoginRequest.java
  src/main/java/com/anipick/backend/oauth/service/AppleLogin.java
  src/main/java/com/anipick/backend/oauth/service/GoogleLogin.java
  src/main/java/com/anipick/backend/oauth/service/KakaoLogin.java
  src/main/java/com/anipick/backend/oauth/service/OAuthService.java
  src/main/java/com/anipick/backend/oauth/service/SocialLogin.java
  src/main/resources/application-local.yml
Labels: feat, fix

#86 fix/회원가입 로그인 dto 필드 수정
  src/main/java/com/anipick/backend/oauth/component/CommonLogin.java
  src/main/java/com/anipick/backend/oauth/controller/OAuthController.java
  src/main/java/com/anipick/backend/oauth/service/AppleLogin.java
  src/main/java/com/anipick/backend/oauth/service/GoogleLogin.java
  src/main/java/com/anipick/backend/oauth/service/KakaoLogin.java
  src/main/java/com/anipick/backend/oauth/service/OAuthService.java
  src/main/java/com/anipick/backend/oauth/service/SocialLogin.java
  src/main/java/com/anipick/backend/token/dto/LoginResponse.java
  src/main/java/com/anipick/backend/token/dto/SignUpResponse.java
  src/main/java/com/anipick/backend/user/controller/UserController.java
  src/main/java/com/anipick/backend/user/service/UserService.java
Labels: fix

#110 fix/탐색 평점순 수정
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/common/domain/SortOption.java
  src/main/java/com/anipick/backend/review/mapper/ReviewMapper.java
  src/main/java/com/anipick/backend/review/service/RatingService.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/anime/AnimeCommandMapper.xml
  src/main/resources/mapper/explore/ExploreQueryMapper.xml
  src/main/resources/mapper/review/ReviewQueryMapper.xml
Labels: feat, fix

#96 feat/회원가입 애니 평가 기능 추가
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/dto/SignupRatingRequest.java
  src/main/java/com/anipick/backend/review/mapper/RatingMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/java/com/anipick/backend/user/mapper/UserMapper.java
  src/main/resources/mapper/review/RatingCommandMapper.xml
  src/main/resources/mapper/review/RatingQueryMapper.xml
  src/main/resources/mapper/user/UserCommandMapper.xml
Labels: feat

#131 fix/SignupVaildator 패키지 util로 import
  src/main/java/com/anipick/backend/auth/service/AuthService.java
Labels: fix

#111 feat/애니 상세 (작품) - 캐릭터/성우진 조회
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/dto/AnimeCharacterActorItemDto.java
  src/main/java/com/anipick/backend/anime/dto/CharacterDto.java
  src/main/java/com/anipick/backend/anime/dto/VoiceActorDto.java
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: feat

#113 feat/애니 상세 (작품) - 시리즈 조회
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDateItemDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeSeriesItemResultDto.java
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: feat

#121 fix/리뷰 수정 API 엔드포인트 및 로직 수정 (review_id -> anime_id)
  src/main/java/com/anipick/backend/review/controller/ReviewController.java
  src/main/java/com/anipick/backend/review/mapper/ReviewMapper.java
  src/main/java/com/anipick/backend/review/service/ReviewService.java
  src/main/resources/mapper/review/ReviewQueryMapper.xml
Labels: fix

#129 feat/마이페이지-유저의 애니 시청 기록 조회
  src/main/java/com/anipick/backend/common/config/JacksonConfig.java
  src/main/java/com/anipick/backend/mypage/controller/MyPageController.java
  src/main/java/com/anipick/backend/mypage/domain/MyPageDefaults.java
  src/main/java/com/anipick/backend/mypage/dto/FinishedAnimesDto.java
  src/main/java/com/anipick/backend/mypage/dto/FinishedAnimesResponse.java
  src/main/java/com/anipick/backend/mypage/dto/LikedAnimesDto.java
  src/main/java/com/anipick/backend/mypage/dto/LikedPersonsDto.java
  src/main/java/com/anipick/backend/mypage/dto/MyPageResponse.java
  src/main/java/com/anipick/backend/mypage/dto/WatchCountDto.java
  src/main/java/com/anipick/backend/mypage/dto/WatchListAnimesDto.java
  src/main/java/com/anipick/backend/mypage/dto/WatchListAnimesResponse.java
  src/main/java/com/anipick/backend/mypage/dto/WatchingAnimesDto.java
  src/main/java/com/anipick/backend/mypage/dto/WatchingAnimesResponse.java
  src/main/java/com/anipick/backend/mypage/mapper/MyPageMapper.java
  src/main/java/com/anipick/backend/mypage/service/MyPageService.java
  src/main/resources/mapper/mypage/MyPageQueryMapper.xml
Labels: feat

#126 feat/애니 상세 (리뷰) - 목록 조회
  src/main/java/com/anipick/backend/anime/controller/AnimeController.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsItemDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsPageDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsRequestDto.java
  src/main/java/com/anipick/backend/anime/dto/AnimeDetailInfoReviewsResultDto.java
  src/main/java/com/anipick/backend/anime/mapper/AnimeMapper.java
  src/main/java/com/anipick/backend/anime/service/AnimeService.java
  src/main/resources/mapper/anime/AnimeQueryMapper.xml
Labels: feat

#128 fix/리뷰 작성 시 유저추천 테이블 상태 저장
  src/main/java/com/anipick/backend/recommendation/domain/UserRecommendMode.java
  src/main/java/com/anipick/backend/recommendation/domain/UserRecommendState.java
  src/main/java/com/anipick/backend/recommendation/mapper/UserRecommendStateMapper.java
  src/main/java/com/anipick/backend/review/service/RatingService.java
  src/main/resources/mapper/recommendation/UserRecommendStateCommandMapper.xml
  src/main/resources/mapper/recommendation/UserRecommendStateQueryMapper.xml
Labels: fix
